/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SPACEWORDS_PRIVATE_H
#define SPACEWORDS_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.0.0.367"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	367
#define COMPANY_NAME	"DSC Software"
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"SpaceWords"
#define INTERNAL_NAME	"SpaceWords"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"SpaceWords"
#define PRODUCT_NAME	"SpaceWords"
#define PRODUCT_VERSION	""

#endif /*SPACEWORDS_PRIVATE_H*/
